- spec/index.emu
* Adding caching mechanism for dependencies (to support pre-populating the dependencies of a module record in the future). #49
* hooks are now options in constructor instead of global symbols. #41, #39
* `global` and `thisValue` can be provided via options, and are created otherwise. #42
* consolidating `directEval` and `indirectEval` into `evalHook` option #17 #12
* introduce `importHook` #46
* preliminar work to interact with the `import()` mechanism.
* adding a new getter for `thisValue` to have symmetry with `global`.
```js
const r = new Realm({
global: undefined, // or any arbitrary object
thisValue: undefined, // or any arbitrary object
evalHook(sourceText) {
return sourceText; 
},
importHook(referrerNamespace, specifierString) {
/* until we spec the reflective API for dynamic and …
```
> Refactor to introduce the `importHook`

- shim/src/functions.js
- shim/src/intrinsics.js
repairFunction and getIntrinsics test the environment for 'function*' support
by evaluating a string and checking for a SyntaxError, however the identity
discontinuity between the outer Realm's "SyntaxError" and the inner Realm's
distinct "SyntaxError" objects broke those tests. I changed them to compare
against the inner Realm's "SyntaxError".
fixes #105
> fix detection of environments that don't support 'function*'

- shim/src/realm.js
- shim/src/stdlib.js
- shim/test/realm/mutable.js
The spec says the initial Realm state should have writable+configurable
global properties (except for three).
We'll want this to happen for frozen/SES realms, eventually, but not here. We
need to be able to run a shim that replaces Realm, or others.
> realm.js: don't freeze globals

- shim/src/context.js
- shim/src/evaluators.js
- shim/src/handler.js
- shim/src/realm.js
- shim/src/stdlib.js
- shim/src/symbols.js
- shim/test/realm/function-eval.js
- shim/test/realm/function-injection.js
(this is based upon PR #104, so best to land it after landing that)
This fixes an injection attack in the child Realm's `Function` constructor which would admit side-effecting code in what ought to be a side-effect-free function call. The attack wouldn't reveal the parent Realm's primordials, however it would prevent the child Realm from protecting itself when using `new Function` to check whether an untrusted string is a syntactically-valid function body.
It also renames many of the evaluators for clarity, per @erights 's advice.
> shim: Fix function-injection attack and rename evaluators for clarity

- shim/src/commons.js
- shim/src/functions.js
Use `Object.*` instead of `Reflect.*` to catch more errors like this.
> shim: avoid making cycles in repairFunction

- shim/src/commons.js
This version should be faster on most platforms.
> commons: use faster implementation of uncurryThis()

- shim/src/evaluators.js
- shim/src/realmFacade.js
- shim/test/realm/function-eval.js
- shim/test/realm/identity-compartment.js
- shim/test/realm/identity-single.js
- shim/test/realm/leak-error.js
Also improve testing of Function identities and escape attempts.
> shim: evaluate() should yield a useful stack trace

- shim/src/accessors.js
- shim/src/commons.js
- shim/src/realm.js
- shim/src/realmFacade.js
- shim/src/unsafeRec.js
- shim/test/realm/test-repair.js
- shim/test/realm/test-shims.js
This changes the main API from `new Realm` to `Realm.makeRootRealm()` and `Realm.makeCompartment()`. It also adds a `shims` option, which provides a list of strings that will be injected into the new RootRealm (as well as every RootRealm created underneath it).
The code that repairs accessors was transformed into a default shim string, to avoid leaking the prototypes.
> Non-class API, add shims

- package.json
- shim/README.md
`shim:build` and `shim:watch` is depending on `yarn`. It seems to be unnecessary and can replace with `npm`.
Also, I've fixed the setup instruction for shim correctly.
Thanks!
> Fix npm-scripts for shim:build

- shim/src/block-imports.js
- shim/src/evaluators.js
- shim/test/realm/test-import-expression.js
We originally considered doing this as part of a shim that would be injected
into each new RootRealm (wrapping the eval/Function globals), but there are
too many cases to do this easily. Now we just apply it in all RootRealms when
building the safe evaluator.
We use a conservative regexp to spot 'import' keywords. This will reject
several safe forms, including commented out import() calls (making them
taboo: even talking about a dynamic import will cause the script to be
rejected). If/when a full parser is available, we should be able to make this
safe and accurate.
We do not look for `import.`, since 'import.meta' is not allowed in script
contexts, so we don't need to guard against it.
The security of this regexp depends it matching the behavior of the parser,
specifically they must …
> reject dynamic import expressions in eval() and new Function()

- shim/src/evaluators.js
- shim/src/realm.js
- shim/src/scopeHandler.js
- shim/test/realm/test-endowments.js
This is built on top of #138, so we might want to rebase it after that lands, making the first commit (14dfd42) redundant.
This adds a second argument to `r.evaluate()` that accepts an `endowments` object, whose properties are copied into the global lexical scope for the code being evaluated.
> Add endowments as second argument to r.evaluate()

- shim/src/accessors.js
- shim/src/functions.js
- shim/src/unsafeRec.js
This PR brings the two repair closer under the same shim approach to improve robustness:
- Both shims are evaled, which protect both shims from accidental identity discontinutity and exposition of unsafe objects.
- They don't take arguments or access any other globals than those available in their scope, reducing parameter passing, and accidental mismatch.
- They appear together and much earlier, as soon as the unsafe global is created, before the unsafe record creation has a chance to reference any primordial.
- They are not part of the allShims array because they are preconditions to have the realm shim execute properly in a new unsafe record. The Realm implementation will ultimately require these preconditions to be resolved in order for it to exist. Once that's the case, those shims …
> Shim repair functions

- shim/src/stdlib.js
- shim/test/realm/stdlib.js
Abort if an accessor is found on the unsafe global object instead of a
data property. We should never get into this non standard situation.
> Guard against accessors on the unsafe global object

- shim/src/evaluators.js
- shim/src/scopeHandler.js
- shim/test/realm/scopeHandler.js
Removed the scope handler class, replaced with a function which returns a plain object.
Added tests
This PR is easier to view without whitespaces: 
https://github.com/tc39/proposal-realms/pull/162/files?w=1
> Scope handler inherits from throwinghandler

- shim/src/realm.js
- shim/src/realmFacade.js
- shim/test/module/realmFacade.js
This change removes the need of private class members (implemented with a weakmap) and simply uses a closure variable which is already accessible.
This is an additional commit built on the previous PR. 
PS: After this PR, only 14 lines of code will not be covered by tests.
```
------------------|----------|----------|----------|----------|-------------------|
File              |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------|----------|----------|----------|----------|-------------------|
All files         |    94.42 |    88.16 |       98 |    94.32 |                   |
accessors.js     |    89.29 |     87.5 |      100 |    89.29 |          38,50,57 |
block-imports.js |      100 |      100 |      100 |      100 |                   |
commons.js       | …
```
> Remove class weakmap

- shim/src/repair/functions.js
- shim/test/realm/test-repair.js
The previous use of 'Function' actually created a "sloppy-mode"
function (whereas using 'function' creates a "strict-mode" function). This
was a leak: we should not be allowing sloppy-mode functions to be accessible
within the new Realm. The sloppy-mode function had '.arguments' and '.caller'
properties, which confused the SES code that removes non-whitelisted
properties.
> shim: build TamedFunction as a strict function, not sloppy

- shim/src/unsafeRec.js
Based on feedback from @ljharb and @warner, this PR replaces #203.  
The Realms shim currently fails in webpack, parcel, and browserify. (SES, which relies on Realms, has failing tests for these bundlers due to this problem [here](https://circleci.com/gh/Agoric/SES/56).) This prevents the Realms shim from being useful in many JavaScript workflows.
The error message is "unexpected platform, unable to create Realm," and this is because after bundling, `isNode` and `isBrowser` are both true due to various rewriting and shimming done by the bundlers. For example, webpack rewrites the platform detection section to: 
```
const isNode =  true && typeof module !== 'undefined';
const isBrowser = typeof document === 'object';
```
and defines `module` (`document` is already defined.)
Key insight: we …
> Rewrite getNewUnsafeGlobal

- spec/index.emu
This is really an editorial difference, since there's no API to set the global this value to anything other than the global object.
> Editorial: globalThis getter returns [[GlobalThisValue]]

- spec/index.emu
Part of addressing #225
In HTML, this host hook would probably do something related to [setting up a window environment settings object](https://html.spec.whatwg.org/#set-up-a-window-environment-settings-object). I wouldn't propose that this would add properties to the global object in HTML.
This PR makes a new host hook section, as another hook may be needed for new modules (in the context of #224)
> Layering: Host hook to initialize new Realms

- README.md
- spec/index.emu
Rationale: To get to a minimal Realms MVP, the functionality can be accessed
by `realm.globalThis.eval` (stash off to the side soon after creating realm to
use reliably).
Omitting this method for now would maximize the flexibility of the continued
development of the Compartment/Evaluator API; that proposal could add an
analogous method to Realm.prototype as part of the same proposal.
Closes #226
Alternative to #224
> Normative: Remove evaluate method

- spec/index.emu
This is convenient for Realm HTML integration, so that the context can
be (statelessly) reused.
An early draft of the HTML integration is at https://github.com/littledan/html/commit/09770cacabb5b9fb7b1ab926cc224e87b63a9153
> Layering: Save execution context in an internal slot

- .editorconfig
Both `spec.html` and `README.md` use the superior tabs for indentation.
> Fix `.editorconfig`

- spec.html
Legacy intrinsic aliases will be removed in <https://github.com/tc39/ecma262/pull/2056>.
> Editorial: Use dotted intrinsics

- spec.html
The term "synthetic realm" is proposed to be used in the HTML/Realm
integration PR to describe the contrast with the main "principal"
Realm. This PR renames the host hook to match, and to avoid the
confusion noted in #281
> Editioral: rename the host hook to HostInitializeSyntheticRealm

- README.md
- package.json
- spec.html
Spec'ing the result of the discussion from https://github.com/tc39/proposal-realms/issues/289 to describe the isolated realms.
> [draft] first draft for isolated realms

- spec.html
> Normative: Clarify text about host added properties

- spec.html
Ref #304
Address review feedback from @ljharb.
---
> why do you need to wrap the completion record value in a new record, as opposed to just passing on the completion record (when its type is normal or return)?
This seems like a bug, I'm removing the Completion wrapping.
> Additionally, since the only possible types of completion record from the invocation is "abrupt" or "normal or return", it kind of seems like you could branch on whether it's abrupt, and not have to explicitly mention normal/return.
I'd say for the editorial style. If check if the type is abrupt, I'd be compelled to add an assertion step saying completion type must be normal or return to clarity it won't be "continue or break". The positive if for normal or return makes the spec steps more clear. I'd prefer to defer …
> Address review feedback 

- biblio.json
- spec.html
a direct `<emu-xref href="#table-internal-slots-of-ecmascript-function-objects"></emu-xref>` is not rendering any text.
> Meta: workaround for ecmarkup to render the appropriate table

- spec.html
Ref https://github.com/tc39/proposal-realms/issues/304#issuecomment-842736704
> Spec fixes, applies review feedback

- spec.html
Instead, its single usage is replaced by a usage of HostImportModuleDynamically
> Normative: Remove HostImportModuleBindingDynamically hook

- spec.html
> Those properties must each be configurable to provide platform capabilities with no authority to cause side effects such as I/O or mutation of values that are shared across different realms within the same host environment.
The current version allows the host to create a mutation of values that _not_ shared across different realms. But IMO that also violates SES requirements.
Example:
```js
// Action of the host in HostInitializeSyntheticRealm
(() => {
let counter = 0 // internal state
globalThis.getCounter = () => counter
globalThis.addCounter = () => void counter++
})()
```
I changed that to:
> Those properties must be configurable. Those properties must have no authority to cause side effects such as I/O or mutation of values (or internal state of the host) that are shared across …
> Editorial: stricter notes in HostInitializeSyntheticRealm

- package.json
Use mkdir -p instead of mkdirp. GH Actions are not including mkdirp anymore
> Meta: Fix package.json script for GH Actions

- spec.html
Ref Comment: https://github.com/tc39/proposal-realms/issues/304#issuecomment-849246499
cc @gibson042 
Resolved in this PR: 
> 1. The "Internal Slots of Wrapped Function Exotic Objects" table defines slot [[WrappedTargetFunction]] as holding "the callable object from the other Realm", despite the definition of wrapped function exotic object not being limited to cross-realm scenarios (e.g., "is an exotic object that wraps a callable object from another Realm.").
> 3. PerformRealmEval step 19 is missing the privateEnv argument in its invocation of EvalDeclarationInstantiation.
> 4. Does PerformRealmEval intentionally skip the check for "If result.[[Type]] is normal and result.[[Value]] is empty" that appears in PerformEval after evaluation? What are the consequences of that omission?
> 5. …
> Editorial: Address Gibson's feedback

- DISCUSSIONS.md
- README.md
- explainer.md
- package.json
- spec.html
This required some manual curation as some instances of Realm needs to be preserving and not being renamed to ShadowRealm. e.g.: `The Realm Record`, `incubator realm`, or general content about multiple realms.
This change achieved consensus at the TC39 meeting in September 2021.
> Normative: Renaming to ShadowRealm

- spec.html
1. ~~`ShadowRealm.[[ShadowRealm]]` is a Realm record, it would be better if the field name is `[[Realm]]` instead.~~
2. AO `PerformRealmEval` should be performed on ShadowRealm associated realms, just like AO `ShadowRealmImportValue`. And AO `ValidateRealmObject` should be performed on ShadowRealm instances but not *Realm*s. It would be better for them to be named with `XxShadowRealmXx` instead.
> Editorial: normalize shadow realm naming

- spec.html
`GetFunctionRealm` in Step 4 of #sec-wrapped-function-exotic-objects-call-thisargument-argumentslist
requires the function object to own an internal slot of [[Realm]] or the current execution realm record will be 
returned instead, which can differ from the creation realm.
> Add WrappedFunction.[[Realm]] internal slot

- spec.html
There's a confusion of completion records and language values in two
uses of the GetWrappedValue AO - quoting ECMA-262:
Within this specification, the notation “Type(x)” is used as
shorthand for “the type of x” where “type” refers to the ECMAScript
language and specification types defined in this clause. [...]
An Object is a language type, a completion record is a specification
type.
This means that the "If Type(value) is Object" path in GetWrappedValue
would never be taken for these calls, even if the completion cecord's
[[Value]] field is an Object. Correct this by passing result.[[Value]]
instead of result (the completion record) itself.
> Editorial: Call GetWrappedValue with completion record's [[Value]]

- spec.html
> Normative: Wrapped function should reuse target name and length

- spec.html
We got the consensus reported in https://github.com/tc39/proposal-shadowrealm/issues/338#issuecomment-994000234 with the following information:
> - length is set similarly to bound functions.
> - Copy the name from the target function, no prefix. Restricted to string-only values, similarly to bound functions.
This PR address the second bullet.
Although, some confusion came in from noted conclusion/resolution from the [meeting in Dec 2021](https://github.com/tc39/notes/blob/master/meetings/2021-12/dec-14.md#conclusionresolution-3). 
> - wrapped functions to use the target function's name/length as in https://github.com/tc39/proposal-shadowrealm/pull/339
> - future exploration of sharing SABs to continue 
Where #339 still had the prefix and was merged as is.
I did not attend that meeting …
> Normative: Remove the name prefix for wrapped functions

- spec.html
Hoist the note so that the thrown TypeError on revoked proxies are thrown in the caller realm.
> Editorial: GetFunctionRealm may throw on revoked proxies

- explainer.md
Missing required binding name argument. Binding name ('redDoSomething') pulled from [previous sections](https://github.com/tc39/proposal-shadowrealm/blob/main/explainer.md#module-graph) importValue call on './file.js'.
> Fix importValue usage under Compartments

- spec.html
This is a revisit of https://github.com/tc39/proposal-shadowrealm/pull/349.
GetFunctionRealm may throw if the target function is a revoked proxy. This PR adds changes that make sure thrown error is created in the realm in which the wrapped function is created. The steps mirror the steps in https://tc39.es/ecma262/#sec-ecmascript-function-objects-call-thisargument-argumentslist. 
/cc @syg @erights
> Normative: GetFunctionRealm may throw on revoked proxies

- errors.md
This PR is the result of the consensus achieved during the Dic 1st, 2022 meeting. We are removing the normative change about stack censoring spec'd on https://github.com/tc39/proposal-shadowrealm/pull/372
> [explainer] removing the section about censoring stack frames

- spec.html
Refactor PR to make it simpler to recognize when an error must be copied over the callable boundary into the caller realm, whether that's a result of `evaluation`, `importValue` or just calling a wrapped function.
This PR is the result of the achieved consensus during the Dic 1st, 2022 Plenary discussion.
> Fixes #353: Normative changes for `Error.message`

- explainer.md
Changes:
* new section about security with all the details
* explanation based on the taxonomy used for this proposal
* removed the concept of "trusted" and "untrusted" from the explainer.
* ShadowRealms -> ShadowRealm
> Clarify security story - take 2 (based on PR #378)

- spec.html
See https://github.com/tc39/proposal-shadowrealm/actions/runs/4012414741/jobs/6890837736. The latest spec (https://github.com/tc39/proposal-shadowrealm/pull/382) is not deployed due to build failures.
> Editorial: Fix ecmarkup typecheck errors

- package.json
- spec.html
HostImportModuleDynamically was replaced by HostLoadImportedModule and no longer allows the referrer to be null. We should use evalContext's Realm to do the import.
Reference: https://github.com/tc39/ecma262/pull/2905/files?diff=split&w=0
> Update ecma262-biblio and pass referrer to HostLoadImportedModule

- package.json
- spec.html
This PR updates ecmarkup and ecma262-biblio to the latest versions, and fixes issues arising from that, including replacing HostImportModuleDynamically which no longer exists. It also updates to the latest recommended practices in ECMA-262 language, adds return types to all the structured headers, and fixes a few typos.
> Update ecmarkup and biblio, structured headers, minor spec language issues

- spec.html
ECMAScript spec used "Well-Known" as capitalization in the header and caption.
https://tc39.es/ecma262/#sec-well-known-intrinsic-objects
> Editorial: Use consistent Well-Known capitalization as ECMAScript Spec

- spec.html
This PR implements the consensus achieved during Dic 1, 2022 plenary with respect to normative text that prevent a violation of the callable boundary.
> fixes #324: normative text to prevent the host environment to leak object reference

- spec.html
ECMA-262 Call, and therefore OrdinaryWrappedFunctionCall, can only return completions of type NORMAL or THROW. All other types such as RETURN are wrapped inside the various objects' [[Call]] internal methods. Therefore handling the RETURN completion type here was erroneous and had no effect.
Similarly, the editors note about different completion types also had no effect.
Closes: #371
> Editorial: Remove erroneous handling of RETURN completion type

- package.json
- spec.html
As of https://github.com/tc39/ecma262/pull/3222 the signature of HostEnsureCanCompileStrings changed. This adapts to the new signature by pulling in the latest version of ecma262-biblio and adding the missing arguments.
Closes: #367
> Editorial: Adapt to new HostEnsureCanCompileStrings

- spec.html
This is just a hypothetical example, so it has no weight in what actually gets exposed, but since we do actually want console to be exposed let's remove console from the list of examples.
h/t @lukewarlow
> Remove console from list of examples

- package.json
- spec.html
The current prose no longer works after https://github.com/tc39/ecma262/pull/3139.
> Rewrite the ShadowRealm constructor with InitializeHostDefinedRealm

- spec.html
> Remove [[ExecutionContext]]

- README.md
Fix link to issues in [README](https://github.com/tc39/proposal-shadowrealm/blob/9321d6f/README.md#history).
Replace 
> we moved on from the exposed globalThis model to a lean isolated realms API (see #&NoBreak;289 and #&NoBreak;291)
by
> we moved on from the exposed globalThis model to a lean isolated realms API (see https://github.com/tc39/proposal-shadowrealm/issues/289 and https://github.com/tc39/proposal-shadowrealm/issues/291)
> docs: Fix link to issues

- spec.html
@mhofman: please let me know if there's any requirements this doesn't capture.
> Assert that the global object inside the Shadow Realm is ordinary.
