shim/src/commons.js
shim/src/evaluators.js
shim/src/intrinsics.js
shim/src/proxy.js
shim/src/realm.js
shim/src/sandbox.js

Added a module to declare shortcuts to Reflect and Object.

Add commons.js

---

shim/src/repair/accessors.js
shim/src/sanitize.js

In this request we:
- Fix two infinite loops
- Remove a redundant seal/freeze
- Set the stage for more sanitization

Fix legacy accessors

---

shim/src/evaluate/verifyStrictFunctionBody.js
shim/src/evaluators.js
shim/src/repair/functionConstructors.js
shim/src/repair/objectAccessors.js
shim/src/sanitize.js

Gradually adapting and merging Mark's code:
https://github.com/tc39/proposal-realms/issues/54

Add sanitize functions

---

shim/src/stdlib.js

Added missing object, added comments to source.

Improve stdlib

---

.travis.yml
package.json
shim/.eslintrc
shim/test/262/create-proto-from-ctor-realm-array.js
shim/test/262/define-own-prop-length-overflow-realm.js
shim/test/262/global.js
shim/test/262/proto-from-ctor-realm.js
shim/test/realm/confinement.js
shim/test/realm/identity-compartment.js
shim/test/realm/identity-single.js

Looking at a way to structure this. In particular, we need to check that the building process doesn't distortions on the expected behaviour.

Initial unit tests

---

shim/src/accessors.js
shim/src/context.js
shim/src/evaluators.js
shim/src/functions.js
shim/src/handler.js
shim/src/intrinsics.js
shim/src/realm.js
shim/src/sanitize.js
shim/src/stdlib.js
shim/src/symbols.js
shim/test/realm/test-typeof.js

this PR is like #111 but builds upon #117. So land #117 first, then I'll rebase this, then we'll land this. Instead of #111.

Rename and questions

---

shim/src/evaluators.js
shim/src/scan.js

a few more notes from today's review

more todo notes, forEach fixes

---

shim/src/evaluators.js
shim/test/realm/function-eval.js

Fix for:
```js
(new Function()).toString();
function() {
undefined
}
```

Fix Function with no arguments

---

shim/src/evaluators.js

todo note on optimizers vs endowments

---

.esmrc
.gitignore
.nycrc
package.json
shim/src/accessors.js
shim/src/evaluators.js
shim/src/functions.js
shim/src/realmFacade.js

Add code coverage

---

package.json
shim/src/utilities.js
shim/test/realm/utilities.js

Using console.warn() makes messages more visible.

Console.error tantrums

---

.travis.yml
shim/src/accessors.js
shim/test/test262/annexB/built-ins/Object/prototype/__defineGetter__/define-new.js
shim/test/test262/annexB/built-ins/Object/prototype/__defineGetter__/define-non-configurable.js
shim/test/test262/annexB/built-ins/Object/prototype/__defineGetter__/this-non-obj.js
shim/test/test262/annexB/built-ins/Object/prototype/__defineSetter__/define-new.js
shim/test/test262/annexB/built-ins/Object/prototype/__defineSetter__/define-non-configurable.js
shim/test/test262/annexB/built-ins/Object/prototype/__defineSetter__/this-non-obj.js
shim/test/test262/annexB/built-ins/Object/prototype/__lookupGetter__/lookup-own-data.js
shim/test/test262/annexB/built-ins/Object/prototype/__lookupGetter__/lookup-proto-data.js
shim/test/test262/annexB/built-ins/Object/prototype/__lookupSetter__/lookup-own-data.js
shim/test/test262/annexB/built-ins/Object/prototype/__lookupSetter__/lookup-proto-data.js

@warner Just some cleanup for maintainability

Simplify Accessors (DRY)

---

shim/src/commons.js
shim/src/evaluators.js

Simplify optimizer

---

.travis.yml
shim/LICENSE-corejs
shim/NOTICE
shim/src/accessors.js
shim/test/realm/accessors.js
shim/test/test262/annexB/built-ins/Object/prototype/__defineGetter__/getter-non-callable.js
shim/test/test262/annexB/built-ins/Object/prototype/__defineSetter__/setter-non-callable.js
shim/test/test262/annexB/built-ins/Object/prototype/__lookupGetter__/this-non-obj.js
shim/test/test262/annexB/built-ins/Object/prototype/__lookupSetter__/lookup-proto-data.js
shim/test/test262/annexB/built-ins/Object/prototype/__lookupSetter__/this-non-obj.js

Simpler implementation
Added more tests

Conditional repair accessors

---

shim/src/evaluators.js

Fix optimizer

---

shim/src/commons.js
shim/src/evaluators.js
shim/src/optimizer.js
shim/test/realm/optimizer.js

Move into own module
Fix bug with regexp
Ignore eval and keywords
@erights

Improve optimizer

---

shim/src/evaluators.js
shim/src/scopeHandler.js
shim/test/realm/evaluators.js
shim/test/realm/scopeHandler.js

Avoid getPrototypeOf in scope handler set
Use 'this' to bind optimizer constants
Safe Function(): tests found errors (tests disabled)
@erights

Improve evaluators

---

shim/src/optimizer.js
shim/test/realm/optimizer.js

Block reserved null, true, false, this
Unblock await

Improve optimizer 3

---

shim/src/realm.js
shim/src/realmFacade.js
shim/test/module/realmFacade.js

Add tests
Fix toString() for constructor and instance

Test realm facade

---

shim/src/realm.js
shim/src/realmFacade.js

Use assert() to guard the weakmaps used as private fields
Move TypeError on new Realm() to the constructor

Improve Realm creation

---

package.json

This should fix the test failures in #198.

shim: update to esm-3.2.0 in package.json

---

spec/index.emu

- Use `RequireInternalSlot`
- Use `CreateRealm`
- Fix `thisValue` being empty.

update and clean spec text

---

README.md
spec/index.emu

Normative: Remove intrinsics() method from spec

---

README.md

This PR is informative and I'm immediately merging it.

Add link to slides from the incubator call

---

EXAMPLES.md
README.md
explainer.md

This is an initial explainer that might and should be expanded. 
I believe it can be a nice starting point to land on the main branch so we follow up with specialized patches.

Draft for the Explainer

---

explainer.md

Guess what? This is the next iteration of many improvements to the explainer. Those here are mostly minor.

Minor improvements to the explainer

---

explainer.md

changes are better seen in the different commits.

New explainer before a TAG review

---

explainer.md

Add expansion for installFakeDOM

---

spec.html

Editorial: Create ValidateRealmObject abstraction

---

spec.html

I noticed a few small nits while reviewing. Feel free to close if these are not reflecting your intention.

small nits

---

spec.html

Ref https://github.com/tc39/proposal-realms/pull/311#discussion_r636479941

Normative: Require property to exist from the imported module namespace

---

package.json
spec.html

Removes the redundant steps of type assertions.

Editorial: update AO parameter declaration notations

---

spec.html

Normative: Type check on importValue 2nd value

---

spec.html

See: https://github.com/tc39/ecma262/commit/7575f74

Editorial: Remove '!' from AO calls that don't return a completion

---

README.md

I'm championing the Node.js ShadowRealm integration and would like to join the champion group of ShadowRealm :)

Add legendecas as a champion

---

explainer.md

explainer.md: miscellaneous grammatical updates

---

package.json
spec.html

- Update `@tc39/ecma262-biblio` to its latest version.
- Update the name of the `IsStrict` SDO to `ScriptIsStrict`.

Update ecma262-biblio dev dep and update SDO name

---

spec.html

These are necessary for the integration on the HTML side.

Add missing arguments to HostInitializeShadowRealm

---

README.md
spec.html

The stage is listed variously as 3 and 2. Neither are correct, the proposal is at stage 2.7. Update some other related things too.

The correct stage
